if(EXISTS "C:/Users/Can Ahmed/Desktop/cen429-2025-2026-5-muhammedbesir-velioglu-cpp/buildCmake/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/Users/Can Ahmed/Desktop/cen429-2025-2026-5-muhammedbesir-velioglu-cpp/buildCmake/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
